server:
  port: 3000  #????
  servlet:
    context-path: /  #?? ??? /blog? ????  ex)http://localhost:8000/blog
    encoding:
      charset: UTF-8  #UTF-8? ?????????   ???????
      enabled: true # true? ???? ?????  ???????
      force: true  #??? ?? ????? ??? ???? ????  ???????

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/  #? ???? ??? ?? ?????? /WEB-INF/views/? ????
      suffix: .jsp  #? ?? ?? ?? ???? .jsp? ????


  jackson:
    serialization:
      fail-on-empty-beans: false

key: ${key}